"""Checkout (payment creation) request and response models."""

from __future__ import annotations

from decimal import Decimal
from typing import List, Optional

from pydantic import BaseModel, Field


class CheckoutRequest(BaseModel):
    """Parameters for creating a checkout transaction.

    The ``hash`` field is auto-generated by the SDK — callers should not set it.
    """

    amount: Decimal = Field(..., description="Transaction amount, e.g. 100.00")
    currency: str = Field(..., description="Three-letter ISO currency code")
    reference: str = Field(..., description="Your internal order or reference ID")
    customer_first_name: str = Field(..., description="Customer's first name")
    customer_last_name: str = Field(..., description="Customer's last name")
    customer_phone_number: str = Field(
        ..., description="Customer's phone number in E.164 format"
    )
    customer_email: str = Field(..., description="Customer's email address")
    transaction_redirect_url: str = Field(
        ..., description="URL to redirect customer after payment"
    )
    additional_data: Optional[str] = Field(
        None, description="Additional metadata for the transaction"
    )
    items: Optional[List[str]] = Field(
        None, description="Array of item IDs from the Items API"
    )


class GatewayData(BaseModel):
    """Gateway information returned in checkout response."""

    redirect_url: str = Field(..., description="URL to redirect the customer for payment")


class CheckoutResponseData(BaseModel):
    """Data payload of a successful checkout response."""

    gateway: GatewayData
    ipg_transaction_id: str = Field(
        ..., description="OnePay's internal transaction identifier"
    )


class CheckoutResponse(BaseModel):
    """Parsed response from the checkout API.

    Provides convenient access to the redirect URL and transaction ID.
    """

    status: int = Field(200, description="HTTP status code")
    data: CheckoutResponseData

    @property
    def redirect_url(self) -> str:
        """The URL to redirect the customer to for payment."""
        return self.data.gateway.redirect_url

    @property
    def ipg_transaction_id(self) -> str:
        """OnePay's transaction identifier — store this for status lookups."""
        return self.data.ipg_transaction_id
